/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mob_moblink_cocos2dx_ActionListener */

#ifndef _Included_com_mob_moblink_cocos2dx_ActionListener
#define _Included_com_mob_moblink_cocos2dx_ActionListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mob_moblink_cocos2dx_ActionListener
 * Method:    nativeOnCreateCxxObject
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mob_moblink_cocos2dx_ActionListener_nativeOnCreateCxxObject
  (JNIEnv *, jobject);

/*
 * Class:     com_mob_moblink_cocos2dx_ActionListener
 * Method:    nativeOnResult
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mob_moblink_cocos2dx_ActionListener_nativeOnResult
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mob_moblink_cocos2dx_ActionListener
 * Method:    nativeOnError
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mob_moblink_cocos2dx_ActionListener_nativeOnError
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mob_moblink_cocos2dx_ActionListener
 * Method:    nativeOnDestoryCxxObject
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mob_moblink_cocos2dx_ActionListener_nativeOnDestoryCxxObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
