/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mob_moblink_cocos2dx_RestoreSceneListener */

#ifndef _Included_com_mob_moblink_cocos2dx_RestoreSceneListener
#define _Included_com_mob_moblink_cocos2dx_RestoreSceneListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mob_moblink_cocos2dx_RestoreSceneListener
 * Method:    nativeOnCreateCxxObject
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mob_moblink_cocos2dx_RestoreSceneListener_nativeOnCreateCxxObject
  (JNIEnv *, jobject);

/*
 * Class:     com_mob_moblink_cocos2dx_RestoreSceneListener
 * Method:    nativeOnReturnSceneData
 * Signature: (Landroid/app/Activity;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mob_moblink_cocos2dx_RestoreSceneListener_nativeOnReturnSceneData
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_mob_moblink_cocos2dx_RestoreSceneListener
 * Method:    nativeOnDestoryCxxObject
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mob_moblink_cocos2dx_RestoreSceneListener_nativeOnDestoryCxxObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
